# Generated by Django 5.0.4 on 2024-05-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('vendor_code', models.CharField(max_length=256, unique=True)),
                ('on_time_delivery_rate', models.FloatField(default=None)),
                ('quality_rating_avg', models.FloatField(default=None)),
                ('average_response_time', models.FloatField(default=None)),
                ('fulfillment_rate', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=256, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'Completed'), ('D', 'Canceled'), ('P', 'Pending')], default='P', max_length=1)),
                ('quality_rating', models.FloatField(null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledgment_date', models.DateTimeField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor_management.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('on_time_delivery_rate', models.FloatField(default=None)),
                ('quality_rating_avg', models.FloatField(default=None)),
                ('average_response_time', models.FloatField(default=None)),
                ('fulfillment_rate', models.FloatField(default=None)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor_management.vendor')),
            ],
        ),
    ]
