# Generated by Django 5.0.4 on 2024-05-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0004_alter_purchaseorder_quality_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalperformance',
            table='historical_performance',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='purchase_order',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendor',
        ),
    ]
